language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2-003131

script:
  - dotnet restore
  - dotnet build */**/project.json --configuration Release
  - dotnet test tests/**/project.json --configuration Release
  
deploy:
  on:
   branch: master
  provider: script
  skip_cleanup: true
  script:
    - mkdir -p .nuget && wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe && dotnet pack src/*/ --no-build --configuration Release && .nuget/nuget.exe push *.nupkg $NUGET_API_KEY -verbosity detailed
