os: Visual Studio 2017

version: 1.0.2.{build}

configuration: Release

platform: Any CPU

branches:
  # Whitelist
  only:
    - vs2017-port
    
# Do not build on tags (GitHub only)
skip_tags: true
  
before_build:
  - dotnet --info
  - dotnet restore  

build:
  parallel: false                  # enable MSBuild parallel builds
  project: SimplePagedList.sln    # path to Visual Studio solution or project   
   
after_build:
  - dotnet pack .\src\SimplePagedList\SimplePagedList.csproj --configuration Release   
   
artifacts:
  - path: artifacts\nuget-package\*.nupkg
